// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package go_techmgmt_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TechMangementClient is the client API for TechMangement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TechMangementClient interface {
	AddNmbers(ctx context.Context, in *Numbers, opts ...grpc.CallOption) (*SumOfIntegers, error)
}

type techMangementClient struct {
	cc grpc.ClientConnInterface
}

func NewTechMangementClient(cc grpc.ClientConnInterface) TechMangementClient {
	return &techMangementClient{cc}
}

func (c *techMangementClient) AddNmbers(ctx context.Context, in *Numbers, opts ...grpc.CallOption) (*SumOfIntegers, error) {
	out := new(SumOfIntegers)
	err := c.cc.Invoke(ctx, "/techmgmt.TechMangement/AddNmbers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TechMangementServer is the server API for TechMangement service.
// All implementations must embed UnimplementedTechMangementServer
// for forward compatibility
type TechMangementServer interface {
	AddNmbers(context.Context, *Numbers) (*SumOfIntegers, error)
	mustEmbedUnimplementedTechMangementServer()
}

// UnimplementedTechMangementServer must be embedded to have forward compatible implementations.
type UnimplementedTechMangementServer struct {
}

func (UnimplementedTechMangementServer) AddNmbers(context.Context, *Numbers) (*SumOfIntegers, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddNmbers not implemented")
}
func (UnimplementedTechMangementServer) mustEmbedUnimplementedTechMangementServer() {}

// UnsafeTechMangementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TechMangementServer will
// result in compilation errors.
type UnsafeTechMangementServer interface {
	mustEmbedUnimplementedTechMangementServer()
}

func RegisterTechMangementServer(s grpc.ServiceRegistrar, srv TechMangementServer) {
	s.RegisterService(&TechMangement_ServiceDesc, srv)
}

func _TechMangement_AddNmbers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Numbers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TechMangementServer).AddNmbers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/techmgmt.TechMangement/AddNmbers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TechMangementServer).AddNmbers(ctx, req.(*Numbers))
	}
	return interceptor(ctx, in, info, handler)
}

// TechMangement_ServiceDesc is the grpc.ServiceDesc for TechMangement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TechMangement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "techmgmt.TechMangement",
	HandlerType: (*TechMangementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddNmbers",
			Handler:    _TechMangement_AddNmbers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "techmgmt/techmgmt.proto",
}
